
default_platform(:ios)

platform :ios do
  lane :release do
    increment_build_number(xcodeproj: "Promise.xcodeproj")
    build_app(workspace: "Promise.xcworkspace", scheme: "Promise")
    upload_to_app_store(skip_metadata: false, skip_screenshots: true,username: "1997pjs@naver.com")
  end
  lane :update_version_number do |options|
    increment_version_number(version_number: options[:version_number])
  end
  lane :submit_for_review do
    deliver(submit_for_review: true)
  end


end
